### ISSUE TITLE
Socket.io v2 Breaks Adapter

### ISSUE THREAD

**Issue by rimelore** [genixpro/socket.io-amqp#13]
Whenever using socket.io 2 or later, the adapter breaks because it does not have a method required for the interface. This adapter has to be used with socket.io 1.

Fix: Change package.json to say "socket.io": "~1.0.2" rather than "socket.io":"^1.0.2"

**Comment by genixpro** [comment]
@GabrielCastro I think you would be an excellent candidate to make this fix

**Comment by GabrielCastro** [comment]
Fix with #14
