### ISSUE TITLE
Callback called again after creation of a namespace

### ISSUE THREAD

**Issue by travellingprog** [genixpro/socket.io-amqp#2]
I know it's not documented in your README instructions, but I saw that a callback could be called to get confirmation that the connection to RabbitMQ has been completed. I'm using it at the moment only to output a confirmation message to my server logs.

However, I noticed these confirmation messages were being output twice as often as I had expected, which lead me to believe at first that I was running twice as many processes as I thought. However, after some digging I've found that each time I start a socketIO namespace in my code, `AMQPAdapter(nsp)` is called again, which leads to my callback also being called again. Since I was only adding a single namespace, this was causing twice the confirmation messages I had been expecting.

Again, no big deal since this functionality is not even documented, but thought I'd share this. One possible improvement I see to avoid confusion in the future is passing `nsp.name` as a second argument to the callback.

**Comment by genixpro** [comment]
Yes I suppose that would happen, I never really considered the making of multiple socket.io contexts. It would be possible to add in the namespace to the callback parameters, thats easy enough. The callback then would have to be renamed to indicate that it gets called multiple times.

**Comment by genixpro** [comment]
It could also be changed so that the callback gets called only once, after the first namespace is created, and never called again.

**Comment by travellingprog** [comment]
I think the former is better. I don't know this AMQP stuff in depth, but I imagine there must be _some_ possibility that you get an error when you create a new namespace even though you didn't get one when you created the default namespace.

In that eventuality, making the callback run again would give the developer a chance to do some custom error handling, rather than just getting an error message.

**Comment by genixpro** [comment]
I have implemented a new version, where the callback receives the name of the namespace that was initialized. I added the callback function to the main documentation, and clearly labelled it as being a callback that will be called for each new namespace. I bumped the minor version number. I will call this closed
